#!/usr/bin/env python3
# Copyright (C) 2016 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import sys


def get_args():
    parser = argparse.ArgumentParser(
        description='Set up pxe boot configuration files')
    parser.add_argument('ipaddr', nargs=1, help='IP address')
    parser.add_argument('--path', '-p',
                        default='/var/lib/tftpboot/grub',
                        help='Path to pxe boot file configs')
    parser.add_argument('--template', '-t',
                        help='Template file to use for pxe config')
    parser.add_argument('--mode', '-m', choices=['net', 'local'],
                        required=True, help='Select boot mode')
    args = parser.parse_args()
    return args


def get_template(template_file, mode):
    templates = {
        'net': """set timeout=1

menuentry "netboot" {
    linux /boot/vmlinuz net.ifnames=0
    initrd /boot/init.img
}""",
        'local': """set timeout=1

menuentry "local disk" {
    insmod chain
    set root=(hd0,2)
    chainloader (${root})/EFI/boot/grubx64.efi
    boot
}"""
    }
    template = templates.get(mode)
    if template_file:
        with open(template_file) as f:
            template = f.read()
    return template


def write_template(filename, template):
    print('Writing template data to', filename)
    with open(filename, 'w') as f:
        f.write(template)


def main():
    args = get_args()
    filename = os.path.join(args.path, '{}.grub.cfg'.format(args.ipaddr[0]))
    template = get_template(args.template, args.mode)
    write_template(filename, template)

if __name__ == '__main__':
    sys.exit(main())
